### ISSUE TITLE
EPIC 1 - User Story 1: Set up basic Express application

### ISSUE THREAD

**Issue by peposlawa** [SchoolOfCode/bc17-w4d2-project-keen-programmers#1]
```[tasklist]
### Tasks
- [x] turn the empty repo into a Node project by installing express
- [x] create a simple JS file and make that "hello world" API example
- [x] run and install the application (our Express APP)
- [x] make a GET request to “http://localhost:3000/”
- [x] check that the Node API has also logged the request in the terminal (console.log)
- [x] check if we get back a response with status code of 200 and text saying “Hello World!”
- [x] create a README that details how to install and run the application using Node through a command line and it needs to specify that the application is an Express API
```
