### ISSUE TITLE
EPIC 1 - User Story 2: Add basic security standards using Helmet

### ISSUE THREAD

**Issue by kieranp-96** [SchoolOfCode/bc17-w4d2-project-keen-programmers#2]
```[tasklist]
### Tasks
- [ ] Install helmet as a dependency
- [ ] Helmet configured as one of the first pieces of middleware.
- [ ] When I inspect the response header I shouldn't be able to see  “X-Powered-By: Express
```
