### ISSUE TITLE
EPIC 2 - User Story 1: Implement functionality to GET all activities for a particular user

### ISSUE THREAD

**Issue by KiranGadhavi** [SchoolOfCode/bc17-w4d2-project-keen-programmers#3]
```[tasklist]
### Tasks
- [x] Create a Json file and import into js file.
- [x] Json file fill it with the user activities data.
- [x] Make sure response object contain  a key called data or error.
- [x] When request succeeds make sure it responds with correct status code.
- [x] Make sure the Array of User Activity objects in the response body (response.data).
- [x] Check, if the status code being an accurate indication of the success/failure (and reason) of the request.
```
