### ISSUE TITLE
EPIC 2 - User story 2: Implement functionality to POST a new activity.

### ISSUE THREAD

**Issue by kieranp-96** [SchoolOfCode/bc17-w4d2-project-keen-programmers#4]
```[tasklist]
### Tasks
- [ ] when we push new activity through POST it should save this new activity to data.json database
- [ ] there should be a new unique id (UUID) and a timestamp generated for each new activity
- [ ] new acitivity must be an object (if not an object it needs to throw an error)
- [ ] if an invalid POST request is created there should be an error displayed
```
