### ISSUE TITLE
EPIC 3 - User Story 1: Implement functionality to PUT (update) an activity

### ISSUE THREAD

**Issue by peposlawa** [SchoolOfCode/bc17-w4d2-project-keen-programmers#5]
```[tasklist]
### Tasks
- [x] when using PUT handler whilst updating the activities the API should update the activity
- [x] when the request succeeds, responding with the correct status code and the activity object that we posted as the response body (response.data)
- [ ] if request should fail due to invalid PUT request, the API should respond with the correct status code and a clear error message (response.error)
```
